# Generated by Django 2.2.28 on 2023-02-08 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20230208_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={},
        ),
    ]
